# Use NGINX base image
FROM tiangolo/nginx-rtmp

# Make directories
RUN mkdir /tmp/hls && \
	mkdir /tmp/dash

# Copy config
COPY ./config/nginx.conf /etc/nginx/nginx.conf
COPY ./config/stat.xsl /var/www/html/stat.xsl