version: "3.9"

services:

  # Home
  # --------------------------------
  # --------------------------------

  home:
    container_name: local-home
    build:
      context: ./containers/local-home
      dockerfile: Dockerfile.dev
    environment:
      - VITE_LOCAL_IP=$LOCAL_IP
      - VITE_LOCAL_RADIO_HOSTNAME=$LOCAL_RADIO_HOSTNAME
      - VITE_LOCAL_RADIO_SERVER_PORT=$LOCAL_RADIO_SERVER_PORT
      - VITE_LOCAL_RADIO_MIDDLEWARE_PORT=$LOCAL_RADIO_MIDDLEWARE_PORT
      - VITE_LOCAL_RADIO_APP_PORT=$LOCAL_RADIO_APP_PORT
      - VITE_LOCAL_TV_HOSTNAME=$LOCAL_TV_HOSTNAME
      - VITE_LOCAL_TV_SERVER_PORT=$LOCAL_TV_SERVER_PORT
      - VITE_LOCAL_TV_MIDDLEWARE_PORT=$LOCAL_TV_MIDDLEWARE_PORT
      - VITE_LOCAL_TV_APP_PORT=$LOCAL_TV_APP_PORT
      - VITE_LOCAL_LIBRARY_HOSTNAME=$LOCAL_LIBRARY_HOSTNAME
      - VITE_LOCAL_LIBRARY_PORT=$LOCAL_LIBRARY_PORT
    volumes:
      - ./containers/local-home/app/public:/usr/src/local-home-app/public
      - ./containers/local-home/app/src:/usr/src/local-home-app/src
      - ./containers/local-home/app/index.html:/usr/src/local-home-app/index.html
      - ./containers/local-home/app/vite.config.js:/usr/src/local-home-app/vite.config.js

  # Radio
  # --------------------------------
  # --------------------------------

  radio-server:
    container_name: local-radio-server
    restart: unless-stopped
    build:
      context: ./containers/local-radio/local-radio-server
      dockerfile: Dockerfile.dev
    volumes:
      - ./containers/local-radio/local-radio-server/config/icecast.xml:/etc/icecast2/icecast.xml
    ports: 
      - 8888:8000

  radio-middleware:
    container_name: local-radio-middleware
    restart: unless-stopped
    build:
      context: ./containers/local-radio/local-radio-middleware
      dockerfile: Dockerfile.dev
    volumes:
      - ./containers/local-radio/local-radio-middleware/server/index.js:/usr/src/local-radio-middleware/index.js
      - ./containers/local-radio/local-radio-middleware/server/models:/usr/src/local-radio-middleware/models
      - ./containers/local-radio/local-radio-middleware/server/modules:/usr/src/local-radio-middleware/modules

  radio-app:
    container_name: local-radio-app
    build:
      context: ./containers/local-radio/local-radio-app
      dockerfile: Dockerfile.dev
    environment:
      - VITE_LOCAL_RADIO_MIDDLEWARE_PORT=$LOCAL_RADIO_MIDDLEWARE_PORT
      - VITE_LOCAL_RADIO_SERVER_PORT=$LOCAL_RADIO_SERVER_PORT
      - VITE_LOCAL_HOME_HOSTNAME=$LOCAL_HOME_HOSTNAME
      - VITE_LOCAL_HOME_PORT=$LOCAL_HOME_PORT
    volumes:
      - ./containers/local-radio/local-radio-app/app/public:/usr/src/local-radio-app/public
      - ./containers/local-radio/local-radio-app/app/src:/usr/src/local-radio-app/src
      - ./containers/local-radio/local-radio-app/app/index.html:/usr/src/local-radio-app/index.html
      - ./containers/local-radio/local-radio-app/app/vite.config.js:/usr/src/local-radio-app/vite.config.js

  # TV
  # --------------------------------
  # --------------------------------

  tv-server:
    container_name: local-tv-server
    build: 
      context: ./containers/local-tv/local-tv-server
      dockerfile: Dockerfile.dev
    ports: 
      - 1935:1935
    volumes:
      - ./containers/local-tv/local-tv-server/config/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/local-tv/local-tv-server/config/stat.xsl:/var/www/html/stat.xsl

  tv-middleware:
    container_name: local-tv-middleware
    build:
      context: ./containers/local-tv/local-tv-middleware
      dockerfile: Dockerfile.dev
    volumes:
      - ./containers/local-tv/local-tv-middleware/server/index.js:/usr/src/local-tv-middleware/index.js
      - ./containers/local-tv/local-tv-middleware/server/models:/usr/src/local-tv-middleware/models

  tv-app:
    container_name: local-tv-app
    build:
      context: ./containers/local-tv/local-tv-app
      dockerfile: Dockerfile.dev
    environment:
      - VITE_LOCAL_TV_MIDDLEWARE_PORT=$LOCAL_TV_MIDDLEWARE_PORT
      - VITE_LOCAL_TV_SERVER_PORT=$LOCAL_TV_SERVER_PORT
      - VITE_LOCAL_HOME_HOSTNAME=$LOCAL_HOME_HOSTNAME
      - VITE_LOCAL_HOME_PORT=$LOCAL_HOME_PORT
    volumes:
      - ./containers/local-tv/local-tv-app/app/public:/usr/src/local-tv-app/public
      - ./containers/local-tv/local-tv-app/app/src:/usr/src/local-tv-app/src
      - ./containers/local-tv/local-tv-app/app/index.html:/usr/src/local-tv-app/index.html
      - ./containers/local-tv/local-tv-app/app/vite.config.js:/usr/src/local-tv-app/vite.config.js

  # Library
  # --------------------------------
  # --------------------------------

  library:
    container_name: local-library
    restart: unless-stopped
    build: 
      context: ./containers/local-library
      dockerfile: Dockerfile.dev
    volumes:
      - ./containers/local-library/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./containers/local-library/files:/var/www/files
      - ./containers/local-library/scripts:/var/www/scripts

  # Admin
  # --------------------------------
  # --------------------------------

  admin:
    container_name: local-admin
    build:
      context: ./containers/local-admin
      dockerfile: Dockerfile.dev
    environment:
      - VITE_LOCAL_RADIO_HOSTNAME=$LOCAL_RADIO_HOSTNAME
      - VITE_LOCAL_RADIO_MIDDLEWARE_PORT=$LOCAL_RADIO_MIDDLEWARE_PORT
      - VITE_LOCAL_RADIO_SERVER_PORT=$LOCAL_RADIO_SERVER_PORT
      - VITE_LOCAL_HOME_HOSTNAME=$LOCAL_HOME_HOSTNAME
      - VITE_LOCAL_HOME_PORT=$LOCAL_HOME_PORT
    volumes:
      - ./containers/local-admin/app/public:/usr/src/local-admin-app/public
      - ./containers/local-admin/app/src:/usr/src/local-admin-app/src
      - ./containers/local-admin/app/index.html:/usr/src/local-admin-app/index.html
      - ./containers/local-admin/app/vite.config.js:/usr/src/local-admin-app/vite.config.js

  # Router
  # --------------------------------
  # --------------------------------

  router:
    container_name: local-router
    restart: unless-stopped
    build: 
      context: ./containers/local-router
      dockerfile: Dockerfile.dev
    ports: 
      - ${LOCAL_HOME_PORT}:8000
      - ${LOCAL_RADIO_SERVER_PORT}:8100
      - ${LOCAL_RADIO_MIDDLEWARE_PORT}:8200
      - ${LOCAL_RADIO_APP_PORT}:8300
      - ${LOCAL_TV_SERVER_PORT}:8400
      - ${LOCAL_TV_MIDDLEWARE_PORT}:8500
      - ${LOCAL_TV_APP_PORT}:8600
      - ${LOCAL_LIBRARY_PORT}:8700
      - ${LOCAL_ADMIN_PORT}:8800
    volumes:
      - ./containers/local-router/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./containers/local-router/config/proxy.conf:/etc/nginx/includes/proxy.conf
      - ./ssl/cert:/etc/nginx/ssl