version: "3.9"

services:

  tv-server:
    container_name: local-tv-server
    restart: unless-stopped
    build: 
      context: ./containers/local-tv/local-tv-server
      dockerfile: Dockerfile.dev
    ports: 
      - 1935:1935
      - ${LOCAL_TV_SERVER_PORT}:80
    volumes:
      - ./containers/local-tv/local-tv-server/config/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/local-tv/local-tv-server/config/stat.xsl:/var/www/html/stat.xsl

  tv-middleware:
    container_name: local-tv-middleware
    restart: unless-stopped
    build:
      context: ./containers/local-tv/local-tv-middleware
      dockerfile: Dockerfile.dev
    ports:
      - ${LOCAL_TV_MIDDLEWARE_PORT}:3000
    volumes:
      - ./containers/local-tv/local-tv-middleware/src/index.js:/usr/src/local-tv-middleware/index.js
      - ./containers/local-tv/local-tv-middleware/src/models:/usr/src/local-tv-middleware/models

  tv-app:
    container_name: local-tv-app
    restart: unless-stopped
    build:
      context: ./containers/local-tv/local-tv-app
      dockerfile: Dockerfile.dev
    environment:
      - VITE_LOCAL_TV_MIDDLEWARE_PORT=$LOCAL_TV_MIDDLEWARE_PORT
      - VITE_LOCAL_TV_SERVER_PORT=$LOCAL_TV_SERVER_PORT
    ports:
      - ${LOCAL_TV_APP_PORT}:8080
    volumes:
      - ./containers/local-tv/local-tv-app/app/public:/usr/src/local-tv-app/public
      - ./containers/local-tv/local-tv-app/app/src:/usr/src/local-tv-app/src
      - ./containers/local-tv/local-tv-app/app/index.html:/usr/src/local-tv-app/index.html
      - ./containers/local-tv/local-tv-app/app/vite.config.js:/usr/src/local-tv-app/vite.config.js