version: "3.9"

services:

  # Home
  home:
    container_name: local-home
    restart: unless-stopped
    build:
      context: ./containers/local-home
      dockerfile: Dockerfile.prod
      args: 
        - VITE_HOSTNAME=$HOSTNAME


  # Dashboard
  dashboard:
    container_name: local-dashboard
    restart: unless-stopped
    build:
      context: ./containers/local-dashboard
      dockerfile: Dockerfile.prod
      args: 
        - VITE_HOSTNAME=$HOSTNAME

  # Radio Middleware
  radio-middleware:
    container_name: local-radio-middleware
    restart: unless-stopped
    build:
      context: ./containers/local-radio/local-radio-middleware
      dockerfile: Dockerfile.prod

  # Radio Server
  radio-server:
    container_name: local-radio-server
    restart: unless-stopped
    privileged: true
    devices:
      - "/dev/snd:/dev/snd"
    build:
      context: ./containers/local-radio/local-radio-server
      dockerfile: Dockerfile.prod

  # TV Middleware
  tv-middleware:
    container_name: local-tv-middleware
    restart: unless-stopped
    build:
      context: ./containers/local-tv/local-tv-middleware
      dockerfile: Dockerfile.prod

  # TV Server
  tv-server:
    container_name: local-tv-server
    restart: unless-stopped
    build: 
      context: ./containers/local-tv/local-tv-server
      dockerfile: Dockerfile.prod

  # Library
  library:
    container_name: local-library
    restart: unless-stopped
    build: 
      context: ./containers/local-library
      dockerfile: Dockerfile.prod      
    volumes:
      - ./containers/local-library/files:/var/www/files

  # Router
  router:
    container_name: local-router
    restart: unless-stopped
    build: 
      context: ./containers/local-router
      dockerfile: Dockerfile.prod
    ports: 
      - 80:80
      - 443:443
      - 1935:1935  