version: "3.9"

services:

  # Home
  home:
    container_name: local-home
    restart: unless-stopped
    build:
      context: ./containers/local-home
      dockerfile: Dockerfile.dev
    environment:
      - VITE_HOSTNAME=$HOSTNAME
    volumes:
      - ./containers/local-home/app/public:/usr/src/local-home-app/public
      - ./containers/local-home/app/src:/usr/src/local-home-app/src
      - ./containers/local-home/app/index.html:/usr/src/local-home-app/index.html
      - ./containers/local-home/app/vite.config.js:/usr/src/local-home-app/vite.config.js

  # Dashboard
  dashboard:
    container_name: local-dashboard
    restart: unless-stopped
    build:
      context: ./containers/local-dashboard
      dockerfile: Dockerfile.dev
    environment:
      - VITE_HOSTNAME=$HOSTNAME
    volumes:
      - ./containers/local-dashboard/app/public:/usr/src/local-dashboard-app/public
      - ./containers/local-dashboard/app/src:/usr/src/local-dashboard-app/src
      - ./containers/local-dashboard/app/index.html:/usr/src/local-dashboard-app/index.html
      - ./containers/local-dashboard/app/vite.config.js:/usr/src/local-dashboard-app/vite.config.js

  # Radio Middleware
  radio-middleware:
    container_name: local-radio-middleware
    restart: unless-stopped
    privileged: true
    build:
      context: ./containers/local-radio/local-radio-middleware
      dockerfile: Dockerfile.dev
    volumes:
      - ./containers/local-radio/local-radio-middleware/server/index.js:/usr/src/local-radio-middleware/index.js
      - ./containers/local-radio/local-radio-middleware/server/models:/usr/src/local-radio-middleware/models
      - ./containers/local-radio/local-radio-middleware/server/modules:/usr/src/local-radio-middleware/modules

  # Radio Server
  radio-server:
    container_name: local-radio-server
    restart: unless-stopped
    build:
      context: ./containers/local-radio/local-radio-server
      dockerfile: Dockerfile.dev
    volumes:
      - ./containers/local-radio/local-radio-server/config/icecast.xml:/etc/icecast2/icecast.xml

  # TV Middleware
  tv-middleware:
    container_name: local-tv-middleware
    restart: unless-stopped
    build:
      context: ./containers/local-tv/local-tv-middleware
      dockerfile: Dockerfile.dev
    volumes:
      - ./containers/local-tv/local-tv-middleware/server/index.js:/usr/src/local-tv-middleware/index.js
      - ./containers/local-tv/local-tv-middleware/server/models:/usr/src/local-tv-middleware/models

  # TV Server
  tv-server:
    container_name: local-tv-server
    restart: unless-stopped
    build: 
      context: ./containers/local-tv/local-tv-server
      dockerfile: Dockerfile.dev
    volumes:
      - ./containers/local-tv/local-tv-server/config/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/local-tv/local-tv-server/config/stat.xsl:/var/www/html/stat.xsl

  # Library
  library:
    container_name: local-library
    restart: unless-stopped
    build: 
      context: ./containers/local-library
      dockerfile: Dockerfile.dev      
    volumes:
      - ./containers/local-library/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./containers/local-library/config/php.ini:/etc/php81/conf.d/settings.ini
      - ./containers/local-library/files:/var/www/files
      - ./containers/local-library/html:/var/www/html

  # Router
  router:
    container_name: local-router
    restart: unless-stopped
    build: 
      context: ./containers/local-router
      dockerfile: Dockerfile.dev
    ports: 
      - 1935:1935
      - 443:443
      - 80:80
    volumes:
      - ./containers/local-router/config/nginx.conf:/opt/nginx/nginx.conf
      - ./containers/local-router/config/http.dev.conf:/opt/nginx/http.conf.d/default.conf
      - ./containers/local-router/config/stream.conf:/opt/nginx/stream.conf.d/default.conf
      - ./containers/local-router/config/includes/proxy.conf:/opt/nginx/includes/proxy.conf
      - ./ssl/dev/cert:/opt/nginx/ssl