# Use Ubuntu base image
FROM ubuntu:jammy

# install icecast2 and enable its autostart
RUN apt update && \
    apt upgrade -y && \
    apt install -y icecast2 && \
    sed -i "s#ENABLE=.*#ENABLE=true#" /etc/default/icecast2 && \
    cat /etc/default/icecast2 && \
    apt autoremove && apt clean && \
    rm -rf /var/lib/apt/lists/*

# Copy config
COPY ./config/icecast.xml /etc/icecast2/icecast.xml

CMD /etc/init.d/icecast2 start && \
	tail -F /var/log/icecast2/error.log