# Use Node base image
FROM node:19-bullseye

# Set the work directory
WORKDIR /usr/src/local-dashboard-app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY ./app/package*.json ./

# Install dependencies
RUN npm install

# Run the app
CMD npm run dev