# Use Node base image
FROM node:bullseye

ARG VITE_HOSTNAME

# install simple http server for serving static content
RUN npm install -g http-server

# Set the work directory
WORKDIR /usr/src/local-dashboard-app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY ./app/package*.json ./

# Install dependencies
RUN npm ci

# Copy files
COPY ./app ./

# Build
RUN npm run build

# Run the app
CMD ["http-server", "--cors", "http://localhost:3000?", "./dist"]