# Use Node base image
FROM node:bullseye

# Install sound library
RUN apt update && \
    apt upgrade -y && \
    apt install -y ffmpeg
    # apt install -y libvorbis-dev && \

# Set the work directory
WORKDIR /usr/src/local-radio-middleware

COPY ./server/package.json /usr/src/local-radio-middleware/package.json

# Install dependencies
RUN npm install

# Run the app
CMD npm run dev