# Use Node base image
FROM node:19-bullseye

# Install sound library
RUN apt update && \
    apt upgrade -y && \
    apt install -y ffmpeg && \
    apt install -y libasound2-dev
    
# Set the work directory
WORKDIR /usr/src/local-radio-middleware

# copy both 'package.json' and 'package-lock.json' (if available)
COPY ./server/package*.json ./

# Install dependencies
RUN npm i

# Copy files
COPY ./server ./

# Run the app
CMD [ "node", "index.js" ]