# Use Node base image
FROM node:bullseye

# Set the work directory
WORKDIR /usr/src/local-tv-middleware

# copy both 'package.json' and 'package-lock.json' (if available)
COPY ./server/package*.json ./

# Install dependencies
RUN npm ci

# Copy files
COPY ./server ./

# Run the app
CMD [ "node", "index.js" ]